[package]
name = "cynic-examples"
version = "0.12.0-dev"
authors = ["Graeme Coupar <grambo@grambo.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
github = ["serde_json"]

[dependencies]
cynic = { path = "../cynic", features = ["surf", "reqwest-blocking"] }
cynic-codegen = { path = "../cynic-codegen" }
serde_json = { version = "1.0", optional = true }

# Reqwest example requirements
reqwest = { version = "0.10.1", features = ["json", "blocking"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

# Surf example requirements
surf = "2.1"
async-std = "1.8"

[dev-dependencies]
insta = "1.4"
